### ISSUE TITLE
Pretrained Model

### ISSUE THREAD

**Issue by mxtsecure** [shahroztariq/CLRNet#1]
Could you share your pretrained model?

**Comment by shahroztariq** [comment]
I will share the link soon.

**Comment by Mahmoudt99** [comment]
Can you share the pretrained model please?

**Comment by shahroztariq** [comment]
I am sorry for the delay. The files are still uploading to Google drive. It will be done by the end of day June 22.

Here is the link 

https://drive.google.com/drive/folders/1CE-HzZh76ejAsrIFSlbaEGmQHyzoj9EQ?usp=sharing

**Comment by zhangruju** [comment]
Hello author,can you share your pretrained model please,if you share your model with me,I would be very grateful to you.
