### ISSUE TITLE
Dataset format

### ISSUE THREAD

**Issue by kjp96** [shahroztariq/CLRNet#2]
Could you please share the dataset format and how to preprocess dataset

**Comment by shahroztariq** [comment]
### This is the dataset_folder format
- Face2Face
  - train
    - fake
      - 000_003
        - 00001.png
        - 00002.png
        - ...
        - 00080.png
      - 001_870
        - 00001.png
        - 00002.png
        - ...
        - 00080.png
    - real
      - 000
        - 00001.png
        - 00002.png
        - ...
        - 00080.png
      - 001
        - 00001.png
        - 00002.png
        - ...
        - 00080.png
       - val 
       - test
- FaceSwap
- DeepFake
- NeuralTextures
- DFDC
- DeepFakeDetection


1. val and test follows the same structure same as the train folder (but different data, obviously)
2. All other datasets also follows the same structures. **[**i.e, {train or test or val} --> {real or fake} --> {video_name} --> {image_name}**]**

### Dataset Preprocessing
We first used FFmpeg to extract frames from videos. Then, we used MTCNN to detect, crop, and align faces inside the video frames. There can be some false positives, but we consider them as noise in the dataset.
